name: "Cloudflare Deployment"

on:
  workflow_run:
    workflows: ["CodeQL"]
    types: [completed]

jobs:
  deployment:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ðŸ“¥ Install Github Action Checkout
        uses: actions/checkout@v2

      - name: ðŸ“¥ Install NodeJS and NPM
        uses: bahmutov/npm-install@v1

      - name: ðŸ“¦ Install NPM Dependencies
        run: npm ci

      - name: ðŸ”¨ Build Project
        run: npm run build
        env:
          APP_NAME: Monoxide API
          APP_DESCRIPTION: Monoxide Ecosystem's mobile-optimized frontend that took all the right vitamins.
          NITRO_PRESET: cloudflare
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: ðŸ“¤ Publish to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
